name: CI

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Determine version bump
        id: version_bump
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
      
          # Determine if there are any commit messages that indicate a major or minor bump
          first_line=$(git log -1 --pretty=%B)
          if [[ "$first_line" =~ ^minor: ]]; then
            BUMP="minor"
          elif [[ "$first_line" =~ ^major: ]]; then
            BUMP="major"
          else
            BUMP="patch"
          fi
      
          # Bump the version using npm version
          NEW_VERSION=$(npm version $BUMP --no-git-tag-version)
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "bump_type=$BUMP" >> $GITHUB_OUTPUT
          echo "Determined bump type: $BUMP"

      - name: Publish to npm (only for major/minor bumps)
        if: steps.version_bump.outputs.bump_type != 'patch'
        run: |
          if [ "${{ steps.version_bump.outputs.bump_type }}" != "patch" ]; then
            echo "Publishing to npm as bump_type is ${BUMP_TYPE}"
          else
            echo "Skipping publish as bump_type is patch"
          fi
    